### PR TITLE
format change

### PR DESCRIPTION
**Pull request by mrdally204**
initial changes.  Please review before I continue.

### CODE REVIEW

**Comment by xioustic** [comment]
I'm not familiar with this format or these changes, but if the lines are somewhat JSON based, you missed a left quote around Je0bpLBfOzE. I'd fix it but I'm stuck on mobile for the time being out of town.

**Comment by Lunatixz** [comment]
Thanks @mrdally204 for helping out... formating looks good. @xioustic is correct Je0bpLBfOzE is missing its leading quote.

Thanks again

**Review by mrdally204 — COMMENTED** [review]
added missing quote

**Comment by Lunatixz** [comment]
Thanks, I'll leave this commit open till update is complete.

**Pull request merged**
